apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: appsec
  name: appsec-github-watcher
  namespace: appsec
spec:
  image: "{{ image }}"
  port: 8080
  azure:
    application:
      enabled: true
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 90
  resources:
    limits:
      memory: "64Mi"
    requests:
      cpu: "10m"
      memory: "32Mi"
  liveness:
    initialDelay: 30
    path: isalive
  readiness:
    initialDelay: 30
    path: isready
  envFrom:
    - secret: appsec-github-watcher
  ingresses:
    - https://appsec-github-watcher.nav.no
  accessPolicy:
    outbound:
      external:
        - host: api.github.com
        - host: slack.com
  env:
    - name: EMAIL_FROM_ADDRESS
      value: "appsec@nav.no"
    - name: ENABLE_EMAIL_FUNCTIONALITY
      value: "false"