name: Run tests & build images
on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**.md'
jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - run: go test ./...
      - name: Build docker image for both applications
        run: |
         docker build --build-arg APP=appsec-github-watcher .
         docker build --build-arg APP=appsec-slack-updater .
