name: Run tests & build image
on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**.md'
jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    environment: prod-gcp:appsec
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go test ./...
      - uses: nais/docker-build-push@1fae4798c79f4af4c3cdbd3fe65e51f8f3ba2368 # ratchet:nais/docker-build-push@v0
        id: docker-push
        with:
          team: appsec
          push_image: false